# Spring Boot App Name
spring.application.name=Intelligent Event Recruitment System

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-snowy-hat-a1kagwn2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Pi7JWr0QzcSq

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HikariCP Connection Pool Settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.keepalive-time=45000
spring.datasource.hikari.validation-timeout=5000

# JWT Configuration
jwt.secret=PHxWXyqQvwgJghMe9hEEL+gNDSTyI3Vd5bHnk+cmM3c=
# jwt.expiration=3600000  // 1 hour below is one day
jwt.expiration=86400000
jwt.refresh.expiration=86400000

# File Upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

file.training-materials-dir=uploads/training-materials


# Base directory for file uploads
file.upload-dir=uploads

# Specific directories
file.profile-pic-upload-dir=${file.upload-dir}/profile-pictures
file.working-photos-dir=${file.upload-dir}/working-photos
file.comcards-dir=${file.upload-dir}/comcards
file.resumes-dir=${file.upload-dir}/resumes
file.company-logo-dir=${file.upload-dir}/company-logos
file.portfolio-media-dir=${file.upload-dir}/portfolio-media


# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600

google.maps.api.key=AIzaSyDvTZdGg0DHu09rOTkxp1slfIyp0pQy8dI

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brianwong0819@gmail.com
spring.mail.password=hudx ldnk zjzm ojgu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf Configuration
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
